<a href="https://colab.research.google.com/github/NatalieAleksandrova2026/Analysis_Cafe_Sales/blob/main/EDA_Cafe_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analysis cafe sales  
*Cafe Sales - Dirty Data for Cleaning Training*  
  
Dirty Cafe Sales Dataset  
**Overview**  
The Dirty Cafe Sales dataset contains 10,000 rows of synthetic data representing sales transactions in a cafe. This dataset is intentionally "dirty," with missing values, inconsistent data, and errors introduced to provide a realistic scenario for data cleaning and exploratory data analysis (EDA). It can be used to practice cleaning techniques, data wrangling, and feature engineering.

**File Information**  
* File Name: dirty_cafe_sales.csv  
* Number of Rows: 10,000  
* Number of Columns: 8    
- `Transaction ID`	A unique identifier for each transaction. Always present and unique.  
- `Item`	The name of the item purchased. May contain missing or invalid values (e.g., "ERROR").  
- `Quantity`	The quantity of the item purchased. May contain missing or invalid values.    
- `Price Per Unit`	The price of a single unit of the item. May contain missing or invalid values.  
- `Total Spent`	The total amount spent on the transaction. Calculated as Quantity * Price Per Unit.  
- `Payment Method`	The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN").  
- `Location`	The location where the transaction occurred. May contain missing or invalid values.	  
- `Transaction Date`	The date of the transaction. May contain missing or incorrect values.

`!pip install numpy, pandas, matplotlib`

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##Downloading dataset

In [2]:
url = 'https://raw.githubusercontent.com/NatalieAleksandrova2026/Analysis_Cafe_Sales/refs/heads/main/data/dirty_cafe_sales.csv'

df_origin = pd.read_csv(url)
df_origin.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [3]:
df = df_origin.copy()

##Primary data diagnosis

In [4]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
print('Data types (raw):\n')
df.dtypes

Data types (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem: Numeric columns (Quantity	object,
Price Per Unit	object, Total Spent)  
Transaction Date	object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

Missing values

In [7]:
print('Missing values:\n')
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(1)
missing_pct
missing_report = pd.DataFrame({
    'count': missing,
    '%': missing_pct
})
missing_report[missing_report['count'] > 0]

Missing values:

                  count     %
Item                333   3.3
Quantity            138   1.4
Price Per Unit      179   1.8
Total Spent         173   1.7
Payment Method     2579  25.8
Location           3265  32.6
Transaction Date    159   1.6

In [8]:
print('Unique values:\n')
print('---Item---\n')
print(df['Item'].value_counts(dropna=False))


print('---Payment Method---\n')
display(df['Payment Method'].value_counts(dropna=False))
print('---Location---\n')
print(df['Location'].value_counts(dropna=False))

Unique values:

---Item---

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64
---Payment Method---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

---Location---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [11]:
print("Find lines with'ERROR' or 'UNKNOWN'\n")
# df.isin(['ERROR', 'UNKNOWN']).any()
display(df.isin(['ERROR', 'UNKNOWN']).sum())
mask_error = df.isin(['ERROR', 'UNKNOWN']).any(axis=1).sum()
print(f'Lines with Error or Unknown: {mask_error.sum()}')

Find lines with'ERROR' or 'UNKNOWN'

Transaction ID        0
Item                636
Quantity            341
Price Per Unit      354
Total Spent         329
Payment Method      599
Location            696
Transaction Date    301
dtype: int64

Lines with Error or Unknown: 2845

## Data Cleaning

`df_origin` - the original dataset  
`df` - the copy

In [26]:
print('Rename columns:\n')
df.columns = df.columns.str.strip()
df = df.rename(columns={
    'Transaction ID': 'transaction_id',
    'Item': 'item',
    'Quantity': 'quantity',
    'Price Per Unit': 'price_per_unit',
    'Total Spent': 'total_spent',
    'Payment Method': 'payment_method',
    'Location': 'location',
    'Transaction Date': 'transaction_name'
})
df

Rename columns:

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_name
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [27]:
print('Rename columns:\n')
df.columns = df.columns.str.strip()
print(list(df.columns))

Rename columns:

['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent', 'payment_method', 'location', 'transaction_name']

In [18]:
'   Transaction Date  '.strip().lower()

'transaction date'

In [19]:
df.columns.str.lower().str.split()

Index([  ['transaction_id'],             ['item'],         ['quantity'],
         ['price_per_unit'],      ['total_spent'],   ['payment_method'],
               ['location'], ['transaction_name']],
      dtype='object')

In [23]:
"_".join("     Transaction   Date   ".lower().split())

'transaction_date'

In [24]:
df.columns.str.lower().str.replace(" ", "_")

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_name'],
      dtype='object')

In [31]:
# ERROR / UNKNOWN change to NaN
df.replace(['ERROR', 'UNKNOWN', 'error', 'unknown', ''], np.nan, inplace=True)
df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_name
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [35]:
#Converting numeric columns
for col in ['quantity', 'price_per_unit', 'total_spent']:
  df[col] = pd.to_numeric(df[col], errors='coerce')

df.dtypes

transaction_id       object
item                 object
quantity            float64
price_per_unit      float64
total_spent         float64
payment_method       object
location             object
transaction_name     object
dtype: object

new_df = pd.DataFrame({"quantity": [0, 3, 5, '', np.nan, "q"]})
` display(new_df)`
` new_df.info()`
pd.to_numeric(new_df['quantity'], errors='coerce')

In [44]:
#Date Convertion
df['transaction_name'] = pd.to_datetime(df['transaction_name'], errors='coerce')
df.dtypes
df['transaction_name']

0      2023-09-08
1      2023-05-16
2      2023-07-19
3      2023-04-27
4      2023-06-11
          ...
9995   2023-08-30
9996   2023-06-02
9997   2023-03-02
9998   2023-12-02
9999   2023-11-07
Name: transaction_name, Length: 10000, dtype: datetime64[ns]

In [46]:
print('Converting columns:\n')
df.dtypes

Converting columns:

transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_name    datetime64[ns]
dtype: object